### ISSUE TITLE
PyKa: undefined names and connections actively refused

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#296]
When trying to use the python client for Kappa, using the version of [kappa_client_v1](https://github.com/Kappa-Dev/KaSim/tree/master/python/kappa_client_v1.py) available currently (2016/Oct/24) and this toy code:
```python
from kappa_client import KappaRuntime, KappaError

kappa_instance = KappaRuntime("http://api.executableknowledge.org:8080")
try:
    print(kappa_instance.version())
except KappaError as exception:
    print(exception.errors)
```
I get the following errors:
```
"C:\Program Files\Python\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\python.exe" C:/cygwin64/home/Hector/KaPaSa/trial.py
Traceback (most recent call last):
  File "C:\Program Files\Python\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\urllib\request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Program Files\Python\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\http\client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "C:\Program Files\Python\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\http\client.py", line 1151, in _send_request
    self.endheaders(body)
  File "C:\Program Files\Python\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\http\client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "C:\Program Files\Python\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\http\client.py", line 934, in _send_output
    self.send(msg)
  File "C:\Program Files\Python\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\http\client.py", line 877, in send
    self.connect()
  File "C:\Program Files\Python\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\http\client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Program Files\Python\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\socket.py", line 711, in create_connection
    raise err
  File "C:\Program Files\Python\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\socket.py", line 702, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\cygwin64\home\Hector\KaPaSa\kappa_client.py", line 33, in version
    response = urlopen(version_url)
  File "C:\Program Files\Python\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\Python\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\urllib\request.py", line 466, in open
    response = self._open(req, data)
  File "C:\Program Files\Python\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\urllib\request.py", line 484, in _open
    '_open', req)
  File "C:\Program Files\Python\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\Program Files\Python\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\urllib\request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Program Files\Python\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\urllib\request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/cygwin64/home/Hector/KaPaSa/trial.py", line 5, in <module>
    print(kappa_instance.version())
  File "C:\cygwin64\home\Hector\KaPaSa\kappa_client.py", line 36, in version
    except urllib2.URLError as exception:
NameError: name 'urllib2' is not defined

Process finished with exit code 1
```

**Comment by pirbo** [comment]
It is because http://api.executableknowledge.org:8080 crashed ...

**Comment by hmedina** [comment]
With update to kappa_client_v1 and relaunching of the server, the issues have been dealt with.
