### ISSUE TITLE
KaSim runtime error: Index out of bounds | segmentation fault

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KaSim#325]
I'm running into a KaSim runtime error. However, I can't replicate it with a specific seed. A sample output:

```
+ Self seeding...
+ Command line to rerun is: 'KaSim' '-p' '0' '-i' 'results/2016_12_16-18_49_57/2/0.ka' '-o' 'results/2016_12_16-18_49_57/2/0.csv' -seed 506062246
Parsing results/2016_12_16-18_49_57/2/0.ka...
done
+ Sanity checks
+ Compiling...
+ Building initial simulation conditions...
         -simulation parameters
         -variable declarations
         -rules
         -perturbations
         -observables
         -update_domain construction
         34 (sub)observables 8 navigation steps
         -initial conditions
+ Building initial state
Done
____________________________________________________________

***Runtime error index out of bounds***


```
If I run 100 randomly seeded, I see failure within 30 repetitions (often as little as 2).

If I run 100 simulations using a seed I saw fail, I run into ``segmentation fault`` as well, even though most of the runs ran well:
```
$ for i in {1..100}; do KaSim -seed 615886366 -p 0 -i results/2016_12_16-18_49_57/2/0.ka -d foo -mode batch; done > stdout
Segmentation fault
Segmentation fault
Segmentation fault

***Runtime error index out of bounds***

Segmentation fault
Segmentation fault
Segmentation fault

```
In other words, out of 100 KaSim runs with the same seed, 93 finished correctly, 6 got runtime errors, 1 got a segfault. KaSim nightly 1edbeae

**Comment by pirbo** [comment]
That is super hyper weird.
Are you using windows nightly build of KaSim throw cygwin?

**Comment by hmedina** [comment]
I used both Cygwin's mintty - bash and the regular cmd.exe, and both produced comparable results.

I'm now using the Linux subsystem for Windows, with native compiled KaSim, and the issue has not presented itself. I suspect "the cross-compiler was in a bad mood", again.

**Comment by hmedina** [comment]
Wait! The plot thickens; I must be doing something wrong on my python side; putting the below code in ``test.py``:

```python
#! python.exe
import subprocess
subprocess.run('bash.exe -c "~/KaSim/bin/KaSim --version"', check=True)
```
If I run it within PyCharm I get errors (notice this time is a new error code, for which the top result was a nodejs thing, but at this point that may be Google biasing results...):
```
Traceback (most recent call last):
  File "C:/cygwin64/home/Hector/KaSaAn/kappa_models/test.py", line 3, in <module>
     subprocess.run('bash.exe -c "~/KaSim/bin/KaSim --version"', check=True)
  File "C:\Program Files\Python\WinPython-64bit-3.5.2.2Qt5\python-3.5.2.amd64\lib\subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'bash.exe -c "~/KaSim/bin/KaSim --version"' returned non-zero exit status 4294967295
```
But if I run it through cmd.exe it works fine:
![capture](https://cloud.githubusercontent.com/assets/1588553/21711202/91ace65e-d3bb-11e6-8b96-76885f58c405.PNG)

Given that this is very similar behavior to the other error code, with an executable that was compiled for linux and is running within the linux subsystem, I suspect the issue is not the cross-compiler's mood. Either way, the issue should be closed until more testing reveals a lead...

**Comment by pirbo** [comment]
```
subprocess.run('bash.exe -c "~/KaSim/bin/KaSim --version"', check=True)
```
does not work on my machine either (but I have a clearer `No such file or directory` error).
Either
```
subprocess.run(['/home/pirbo/KaSim/bin/KaSim', '--version'], check=True)
```
or
```
subprocess.run('~/KaSim/bin/KaSim --version', check=True,shell=True)
```
do.

**Comment by hmedina** [comment]
Since I'm compiling KaSim under the Linux Subsystem for Windows (LSW), it is not a Windows executable (i.e. not KaSim.exe). I have to call it through the LSW terminal, bash.exe in this case, to have it handle all the metadata that Linux files use that Windows files don't (more [here](https://blogs.msdn.microsoft.com/commandline/2016/11/17/do-not-change-linux-files-using-windows-apps-and-tools/)), hence the command I send to cmd.exe is ``bash.exe -c "KaSim ..."``

In the original post however, I was calling KaSimNightly directly from cygwin's bash, no python involved, and the issue was present (see the ``for i in {1..100}; do KaSim [...]`` part). Therefore it is not a python problem. 🤔

Calling KaSimLSW through LSW's bash does not present the problem (albeit, different commit), so it /may/ be a cross-compilation, or Cygwin interaction issue. In any case, the issue is not present when using the LSW directly.

![capture-01](https://cloud.githubusercontent.com/assets/1588553/21731244/6d5b5c98-d421-11e6-8c19-59039cf9489b.PNG)
