### ISSUE TITLE
New kappy installation errors

### ISSUE THREAD

**Issue by bgyori** [Kappa-Dev/KaSim#574]
The new version of Kappy released yesterday (https://pypi.org/project/kappy/) throws the error below when installing with pip:
```
Collecting kappy (from emmaa==1.2.1)
  Downloading https://files.pythonhosted.org/packages/61/08/ed8f2a53e4f016671c1e69031ec9c767e71bab5c6eb9da45704f421985ab/kappy-4.0.90.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-hxytno6a/kappy/setup.py", line 55, in <module>
        long_description=readme(),
      File "/tmp/pip-build-hxytno6a/kappy/setup.py", line 48, in readme
        with open('python/README.rst') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'python/README.rst'
```
This indicates that README.rst is not included in the released tar.gz file. In fact, when listing the files in the tar.gz file, it has the following:
```
kappy-4.0.90/
kappy-4.0.90/PKG-INFO
kappy-4.0.90/README.md
kappy-4.0.90/python/
kappy-4.0.90/python/dummy.c
kappy-4.0.90/python/kappy/
kappy-4.0.90/python/kappy/__init__.py
kappy-4.0.90/python/kappy/kappa_common.py
kappy-4.0.90/python/kappy/kappa_rest.py
kappy-4.0.90/python/kappy/kappa_std.py
kappy-4.0.90/python/kappy.egg-info/
kappy-4.0.90/python/kappy.egg-info/PKG-INFO
kappy-4.0.90/python/kappy.egg-info/SOURCES.txt
kappy-4.0.90/python/kappy.egg-info/dependency_links.txt
kappy-4.0.90/python/kappy.egg-info/not-zip-safe
kappy-4.0.90/python/kappy.egg-info/requires.txt
kappy-4.0.90/python/kappy.egg-info/top_level.txt
kappy-4.0.90/setup.cfg
kappy-4.0.90/setup.py
```
note that a README.md is there but python/README.rst is not included.

**Comment by pirbo** [comment]
`python/README.rst` is now included in the source distribution but, still, if you have to use the source distribution, only `kappa_rest` will really work.
We need to build the "wheel" for the platform you're using in order to get a working out of the box `kappa_std`...

**Comment by bgyori** [comment]
Thanks! Yes, having the kappa_std be part of the package would be essential for us. I recently built a wheel for Mac and Linux locally, would it be helpful if I sent you those to upload?

**Comment by bgyori** [comment]
Fo reference the current error message during install is as follows:
```
Building wheels for collected packages: kappy
  Running setup.py bdist_wheel for kappy: started
  Running setup.py bdist_wheel for kappy: finished with status 'error'
  Complete output from command /home/travis/virtualenv/python3.5.6/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-lgkmhy_k/kappy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-3c27g76f --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.5
  creating build/lib.linux-x86_64-3.5/kappy
  copying python/kappy/kappa_common.py -> build/lib.linux-x86_64-3.5/kappy
  copying python/kappy/kappa_std.py -> build/lib.linux-x86_64-3.5/kappy
  copying python/kappy/__init__.py -> build/lib.linux-x86_64-3.5/kappy
  copying python/kappy/kappa_rest.py -> build/lib.linux-x86_64-3.5/kappy
  running egg_info
  writing dependency_links to python/kappy.egg-info/dependency_links.txt
  writing python/kappy.egg-info/PKG-INFO
  writing requirements to python/kappy.egg-info/requires.txt
  writing top-level names to python/kappy.egg-info/top_level.txt
  reading manifest file 'python/kappy.egg-info/SOURCES.txt'
  writing manifest file 'python/kappy.egg-info/SOURCES.txt'
  running build_ext
  running build_agents
  make: *** No rule to make target `all'.  Stop.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-lgkmhy_k/kappy/setup.py", line 78, in <module>
      ext_modules=[distutils.core.Extension('kappy.dummy', sources = ['python/dummy.c'])],
    File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/setuptools/__init__.py", line 131, in setup
      return distutils.core.setup(**attrs)
    File "/opt/python/3.5.6/lib/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/opt/python/3.5.6/lib/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/opt/python/3.5.6/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 202, in run
      self.run_command('build')
    File "/opt/python/3.5.6/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/python/3.5.6/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/opt/python/3.5.6/lib/python3.5/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/opt/python/3.5.6/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/python/3.5.6/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-lgkmhy_k/kappy/setup.py", line 31, in run
      self.run_command('build_agents')
    File "/opt/python/3.5.6/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/python/3.5.6/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-lgkmhy_k/kappy/setup.py", line 24, in run
      subprocess.check_call(["make","all","agents"])
    File "/opt/python/3.5.6/lib/python3.5/subprocess.py", line 271, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['make', 'all', 'agents']' returned non-zero exit status 2
  
  ----------------------------------------
  Failed building wheel for kappy
  Running setup.py clean for kappy
Failed to build kappy```

**Comment by pirbo** [comment]
Hi, 
I'm sorry, the python ecosystem is really not my speciality but I'm confused: I do provide a wheel for python 3.5 under linux (as well as 2.7 and 3.4...3.7 This is easy there is a docker image to do them). Why is your pip trying to recompile it by itself?
I also uploaded a wheel for 3.7 and 3.6 for MacOS but I cannot manage to build some for 3.5 and 3.4... I installed these version using the binaries on python.org and I get `pip3.5 install wheel`: `Could not find a version that satisfies the requirement wheel (from versions: )`!

**Comment by bgyori** [comment]
I am looking into it now and I think the issue is that `pip install` doesn't recognize the new platform-specific versions properly. For instance, the Linux Python 3.5 version used to be called
```
kappy-4.0.0-cp35-cp35m-manylinux1_x86_64.whl 
```
and now it is called
```
kappy-4.0.91-cp35-cp35m-manylinux2010_x86_64.whl 
```
I suspect the reason it doesn't recognize the new installer is that `manylinux1` was changed to `manylinux2010` making pip install believe that it needs to compile from the raw source distribution (kappy-4.0.91.tar.gz ).

**Comment by pirbo** [comment]
The difference between `manylinux1` and `manylinux2010` are defined at https://github.com/pypa/manylinux/tree/master (The first is centos5 based and the second centos6...)

It is rather cheap for me to generate the `manylinux1` wheels if you need them...

**Comment by bgyori** [comment]
I see, I wasn't aware of that distinction. Yes, adding manylinux1 wheels might solve the problem if you don't mind doing that. Thanks!

**Comment by pirbo** [comment]
uploaded
